version: '3'

dotenv: ['.env']

tasks:
  default:
    desc: 列出可用任务
    cmds:
      - task --list

  upload:
    desc: "上传文件到蓝奏云, 用法: task upload FILE=<文件路径>"
    cmds:
      - go run ./cmd/app -file "{{.FILE}}"

  build:
    desc: 编译到 bin/app
    cmds:
      - go build -o bin/app ./cmd/app
  
  build-huawei:
    desc: 华为云函数 custom runtime 版本编译
    platforms: [linux]
    env:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -ldflags="-linkmode=internal -s -w" -o build/lanup cmd/app/main.go
